name: Pre Commit Check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          enable-pep582: true

      - name: Install project dependencies
        run: |-
          pdm pre-install
          pdm install -G:all

      - name: Run pre-commit
        run: |-
          local ret=0
          pdm run pre-commit run --all-files --show-diff-on-failure --color=always || ret=$?

          # push back changes
          if [[ -n "$(git status -s)" ]]; then
            git add .
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git commit -m "chore: pre-commit auto fix [skip ci]"
            git push
          else
            echo "No changes detected."
          fi

          exit $ret
